### PR TITLE
Add Theme - Mexican

### PR DESCRIPTION
**Pull request by JannatinNaim**
Mexican theme. ;)

image

### CODE REVIEW

**Comment by Miodec** [comment]
To be honest im not sure i see the Mexican theme that much

**Comment by JannatinNaim** [comment]
> To be honest im not sure i see the Mexican theme that much

Yeah, I was thinking the same. I'll update the colors.

**Comment by JannatinNaim** [comment]
I've redone the color scheme, take a look.

image

**Comment by Miodec** [comment]
Alright, thanks

**Pull request merged**
