### PR TITLE
Added Yoruba 1k

### PR DESCRIPTION
**Pull request by joshuamango**
Adding a language or a theme? Make sure to edit the `list.json` file as well, otherwise, it will not work!

Please reference any issues related to your pull request.

If your change is visual (mainly themes) it would be extra awesome if you could include a screenshot.

### CODE REVIEW

**Comment by Miodec** [comment]
Please dont prettify `list.json`. Commas are first to avoid merge conficts.

**Comment by joshuamango** [comment]
Apologies. Reverted the formatting in `list.json`.

**Comment by Miodec** [comment]
Oh, also just realized that you've got spaces in words - this will not work with the current input implementation I'm afraid :< Right now every time you press space I'm moving to the next word, meaning if you have spaces inside a word, you won't be able to type the whole thing.

**Comment by joshuamango** [comment]
That makes sense. I removed words with spaces and some duplicates. Although, the number of words is now ~730. Is that okay or should I try to get some more/or change the name to just "yoruba" (without the 1K)?

**Comment by Miodec** [comment]
Thats fine. You can add more later if you find any, to bring it closer to 1k.

**Comment by Miodec** [comment]
Also the name in the language json doesnt match the filename - wont work.

**Pull request merged**
