### PR TITLE
Expose layouts globally to make editing layouts easier.

### PR DESCRIPTION
**Pull request by angularorbit**
This would greatly simplify, e.g. an extension to add a new customized layout.

### Description

Basically exposes the layouts list as a global variable.

### CODE REVIEW

**Comment by Miodec** [comment]
Im not sure whats the benefit of this

**Comment by angularorbit** [comment]
It is meant to allow someone to add his own layout via a browser extension by modifying the `layouts` object, which would otherwise be difficult to extract using js, as it seems the whole of monkeytype.js is inside a webpack closure, and the layouts variable is inaccessible (without a debugger). I have successfully been able to modify the layout by adding a break point at the declaration and then exposing the variable. But I still don't know how it is possible to do that automatically via an extension, Thus I put the pull request...

**Comment by Miodec** [comment]
But, why would you want to modify the layout at runtime? Why not just add it to the layouts file?

**Comment by angularorbit** [comment]
Because I haven't set up a dev server in my machine.

**Comment by Miodec** [comment]
You don't even need a local dev server to create layouts, just edit the layouts file. Also, setting up local dev server is not difficult, I don't think exposing layouts globally is needed.

**Pull request closed without merging**
