### PR TITLE
Add Bangla language

### PR DESCRIPTION
**Pull request by Iftakharpy**
### Description
Added the Bengali language.

### Checklist 
- [x] I have read the [`CODE_OF_CONDUCT.md`](https://github.com/Miodec/monkeytype/blob/master/CODE_OF_CONDUCT.md) and the [`CONTRIBUTING.md`](https://github.com/Miodec/monkeytype/blob/master/CONTRIBUTING.md)
- [x] I checked if my PR has any bugs or other issues that could reduce the stability of the project
- [x] I understand that the maintainer has the right to reject my contribution and it may not get accepted.
- [x] If my PR is a new language or theme I modified the appropriate files to incorporate the language or theme

#### Screenshots
ss1
ss2
ss3
ss4

### CODE REVIEW

**Comment by Miodec** [comment]
Please keep the default word list to 200 words, and then if you want you can add another list with more, for example 10k.

**Comment by Iftakharpy** [comment]
Sorry, I thought I kept 200 words but now when I see the diff I have noticed that there are 100 words. should I add 100 words?

**Comment by Miodec** [comment]
Yeah, 100 might feel repeat too much.

**Comment by Iftakharpy** [comment]
What about the last commit message how do I update that in this remote branch?

**Comment by Miodec** [comment]
Just make another commit you dont need to update the previous one. Say something like 'fixed previous commit' or something.

**Review by Miodec — APPROVED** [review]

**Pull request merged**
