### PR TITLE
 Add VSCode Theme (Dark)

### PR DESCRIPTION
**Pull request by Odyssey346**
image

### Description
I have added a new theme to Monkeytype, based on VSCode's default dark theme. 

The values are taken from [here](https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/themes/dark_vs.json)

### Checklist 
- [x] I have read the [`CODE_OF_CONDUCT.md`](https://github.com/Miodec/monkeytype/blob/master/CODE_OF_CONDUCT.md) and the [`CONTRIBUTING.md`](https://github.com/Miodec/monkeytype/blob/master/CONTRIBUTING.md)
- [x] I checked if my PR has any bugs or other issues that could reduce the stability of the project
- [x] I understand that the maintainer has the right to reject my contribution and it may not get accepted.
- [x] If my PR is a new language or theme I modified the appropriate files to incorporate the language or theme

### CODE REVIEW

**Comment by Odyssey346** [comment]
image

**Comment by UnrealApex** [comment]
>Screenshot 2021-07-04 12 32 54 PM
)

Please make sure screenshots focus only on the content.

**Review by UnrealApex — APPROVED** [review]

**Comment by Odyssey346** [comment]
> Please make sure screenshots focus only on the content.

sorry about that

**Comment by Odyssey346** [comment]
>
> From what i can see the text color is not white. Please keep the text color close to white.

Hmm, that kind of messes up the contrast.

**Comment by Miodec** [comment]
I don't know, its your theme. Play around with it until you're happy with it. I would probably just make the sub color darker.

**Comment by Odyssey346** [comment]
Okay, it should be good now. @Miodec take a look

**Review by Miodec — APPROVED** [review]

**Pull request merged**
