### PR TITLE
English 25k - Replace British Spellings

### LINKED ISSUE #2565: Remove/fix words in english 25k
```
Non-words:
fgrid is not a word.
tinc is a vpn.

British English:
disorganisation should be disorganization.
manoeuvre should be maneuver. 
Saltpetre should be saltpeter (saltpetre is chiefly british per merriam webster)
harmonised should be harmonized. 
unpluralised should be unpluralized.

Abbreviations:
dept is an abbreviation (for department)

Proper Names:
Travers 
siddhartha 
Casey is a name
Arioch (biblical character)

Place Names and Demonyms: 
Catalonia (Spanish region)
Zuni (demonym and language)
Genoese (demonym)
Tocantins (State in Brazil)

Other: 
fagged is questionable
```

 - Remove non words, names, places.
 - Replace abbreviatoins.
 - Replace british words and add the to the british list.

### PR DESCRIPTION
**Pull request by gimmerain4days**
### Description

Part of #2565

Find and replace British suffix "-ise" with American "-ize" where appropriate. Removed 2 words not appearing in Merriam-Webster dictionary. 

My first contribution to any github project, let me know if I have made any mistakes! And thank you for your time! Also, I am dag330 on discord, who messaged about this yesterday.

### CODE REVIEW

**Comment by Miodec** [comment]
Just fyi - "partly closes" is not a thing (github will just pick up 'closes' and close the issue completely). Usually we just say "part of"

**Comment by gimmerain4days** [comment]
Thank you Mio. I have revised the original description.

**Comment by Miodec** [comment]
Also, did you check that after changing the spelling of the words they don't duplicate?

**Comment by gimmerain4days** [comment]
Good point. I will check and revise if necessary.

**Review by Miodec — APPROVED** [review]

**Pull request merged**
