### PR TITLE
Replace "sorani" with "kurdish_central"

### PR DESCRIPTION
**Pull request by roj1512**
This replaces the less-common and non-standard term "sorani" with "kurdish(central)". The term "sorani" is not used in official documents of governments, and neither too much in casual people talk. Even ISO doesn’t use that term: its 639-3 code, `ckb`, stands for (C)entral (K)urdish (B)ranch.

Even me, I personally would have never known that Kurdish is available in the game until I scrolled through all of the languages. When I searched for "Kurd..", I didn’t get any result.

### CODE REVIEW

**Comment by Ferotiq** [comment]
at the least, put a space between "kurdish" and the parens

**Comment by roj1512** [comment]
@Ferotiq Won’t it break or I misunderstood? https://github.com/Miodec/monkeytype/pull/2763#pullrequestreview-920655977

**Comment by Ferotiq** [comment]
it could break, I haven't checked, I will. But if it would break it, then use an underscore (`kurdish_central`) instead, parens don't really fit.

**Comment by roj1512** [comment]
@Ferotiq Will then the "Central" appear in the language list?

**Comment by Ferotiq** [comment]
yeah, things like `english_10k` work.

**Comment by roj1512** [comment]
@Ferotiq Done!

**Review by riimuru — APPROVED** [review]

**Review by riimuru — APPROVED** [review]
lgtm

**Review by riimuru — APPROVED** [review]
lgtm

**Review by Miodec — APPROVED** [review]

**Comment by Miodec** [comment]
Please rename the `.json` file - the name is incorrect.

**Comment by roj1512** [comment]
@Miodec which file do you mean is not ending with .json?

**Comment by roj1512** [comment]
@Miodec done!

**Pull request merged**
