### PR TITLE
Update pull_request_template.md

### PR DESCRIPTION
**Pull request by UnrealApex**
### Description

Used a better word for what a PR does when it closes an issue.

### CODE REVIEW

**Comment by Miodec** [comment]
I meeean, i dont know if this tip makes sense because they would use the . shortcut *before* making a PR.

**Comment by UnrealApex** [comment]
Well, that does make sense, but hey, easter egg.

**Comment by Miodec** [comment]
How about just include both

**Comment by UnrealApex** [comment]
Sure

**Review by Miodec — APPROVED** [review]

**Pull request merged**
