### PR TITLE
Updated internal link names

### PR DESCRIPTION
**Pull request by UnrealApex**
Updated the internal link names in the privacy policy to be more contextual to the user and small fixes. I noticed the `package-lock.json` files had a abnormal amount of deletions when I ran `npm i` is that normal?

### CODE REVIEW

**Comment by Miodec** [comment]
Please update your npm then rerun `npm i` to avoid this huge `package-lock` diff.

**Comment by Miodec** [comment]
Could you also merge master into this branch?

**Comment by UnrealApex** [comment]
I'm pretty sure GitHub handles that automatically when you merge my PR. The only time conflicts will occur is when a file I've  modified has been modified elsewhere(merge conflict).

**Comment by Miodec** [comment]
You could be right actually.

**Pull request merged**
