### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by samuelxyz**
### Description

Adds more layouts

### CODE REVIEW

**Comment by Miodec** [comment]
Dang, seems like a lot of really obscure layouts? How does it look on the settings page? Isnt it too busy now? Maybe we need to add some sort of grouping

**Review by thuongtruong1009 — DISMISSED** [review]
🔥

**Comment by samuelxyz** [comment]
> How does it look on the settings page? Isnt it too busy now?

It's still much less than the number of themes, so by that comparison I think it's not too bad.

**Comment by Miodec** [comment]
Alright, thanks

**Pull request merged**
