### PR TITLE
Added watch-replay

### PR DESCRIPTION
**Pull request by lukew3**
Also added `*package-lock.json` to gitignore

### CODE REVIEW

**Comment by lukew3** [comment]
A lot of line deletions are shown because package-lock.json was left in the repo, when it shouldn't have been.

**Comment by lukew3** [comment]
[Demo](https://www.youtube.com/watch?v=SvUdwFTnE4o)

**Comment by lukew3** [comment]
Also, be sure to check the merge master branch commit. I'm slightly worried that I messed something up.

**Comment by lukew3** [comment]
Found the error, am now confident that my PR is up to date with your current master branch.

**Comment by Miodec** [comment]
Nice! Couple things:
- I think it would be better for visibility to show the text in `text color`. Maybe show all the words typed in `sub color` first, and then they change color to `text color`. Maybe high light errors in `error color` ?
- If you look at the previous commits a lot of it is moving the code into modules. Do you think you could convert this into a `Replay` module?

Nice work so far, you got it ready pretty quick

**Comment by lukew3** [comment]
Thanks for the feedback. I'm pretty busy this week but I should have a pr with the requested changes before next weekend.

**Pull request closed without merging**
