### PR TITLE
Blueberry light and dark theme

### PR DESCRIPTION
**Pull request by raymon-zhang**
image
image

### CODE REVIEW

**Review by antorkhan — APPROVED** [review]
The theme looks good to me!

**Review by UnrealApex — APPROVED** [review]

**Comment by Miodec** [comment]
Dark looks too similar to `superuser`. With light the logo is pretty unreadable.

**Comment by Miodec** [comment]
For the dark version: i think it doesnt matter much if you switch the colors around, it still is too close to superuser to be included, sorry.

 For the light: now the icons are pretty hard to read. I think its just the color choice that need to be reconsidered. Also slightly similar to mizu.

**Comment by raymon-zhang** [comment]
> For the dark version: i think it doesnt matter much if you switch the colors around, it still is too close to superuser to be included, sorry.
> 
> For the light: now the icons are pretty hard to read. I think its just the color choice that need to be reconsidered. Also slightly similar to mizu.

@Miodec Alright, I've changed the colors, do you think it looks ok now?
image
image

**Comment by Miodec** [comment]
I think light doesnt work as well, but im willing to merge the dark version.

**Comment by raymon-zhang** [comment]
@Miodec Is this better for the light?
image

**Pull request merged**
