### PR TITLE
Added ability to copy Miodec's discord tag in privacy policy onclick and fixed links

### PR DESCRIPTION
**Pull request by UnrealApex**
This is still in progress as there are some bugs I still need to fix. Please give some suggestions and possible fixes.

https://user-images.githubusercontent.com/79121360/116168261-dd2e7480-a6b6-11eb-846e-3a0609e712fb.mp4

Resolves issue #1296

### CODE REVIEW

**Comment by Miodec** [comment]
I would prefer to just show a balloon "Click to copy", instead of using a button.

**Comment by Miodec** [comment]
image
Like this

**Comment by UnrealApex** [comment]
Yeah, just what I was thinking.

**Comment by UnrealApex** [comment]
I implemented it with an input box because I was having a few problems with the button tag.

**Comment by UnrealApex** [comment]
Need some help debugging the problem I have at the moment with the onclick function, but was able to successfully add the tooltip.

**Comment by Miodec** [comment]
Try using `navigator.clipboard.writeText`

**Comment by UnrealApex** [comment]
It worked! 🎉  Thanks 👍 .

**Comment by UnrealApex** [comment]
I would say this PR is ready to be merged, but the only improvements I think now would be to make the tooltip transparency match those on the rest of the website and the match the font.

**Comment by Miodec** [comment]
Wait. You shouldve just used the balloon.css library to get the same popup

**Comment by UnrealApex** [comment]
Sure, I'll try that.

**Comment by UnrealApex** [comment]
How do you do that again? I apologize, I don't have very good knowledge of css yet(still learning web dev).

**Comment by Miodec** [comment]
Here is the library

https://kazzkiq.github.io/balloon.css/

All you need to do is include it (just like in index.html)

**Comment by UnrealApex** [comment]
I am still figuring out how to change the tooltip location so I committed it with a button for now.

**Pull request merged**
