### PR TITLE
Adding UwU Colorscheme

### PR DESCRIPTION
**Pull request by Mangeshrex**
Adding a Theme

### CODE REVIEW

**Comment by Miodec** [comment]
Please include screenshots when adding themes

**Comment by Mangeshrex** [comment]
IMG_20211125_191415_939

**Comment by Mangeshrex** [comment]
initially this is a colorscheme project. So till now it is just available for some terminal emulator vim neovim and vscode. And I am working on other ports too :)

**Comment by Mangeshrex** [comment]
Screenshot (13)


Here now you can check this

**Comment by Mangeshrex** [comment]
Do tell me if that looks good or not

**Comment by Miodec** [comment]
I think it's too similar to the "Terra" theme, sorry.

**Comment by Mangeshrex** [comment]
Aye ;-; I was still changing it and was ready to change it why directly closing. Uhmm ill make a better one and come again :))

**Pull request closed without merging**
