### PR TITLE
Convert external dependencies to npm packages

### PR DESCRIPTION
**Pull request by Marco-Pagani**
This is related to #579. All static libraries have been replaced with npm packages

### CODE REVIEW

**Comment by Miodec** [comment]
Getting `$ is undefined` after merging. Im guessing because the `global-dependencies.js` is loaded after the refactored files? All though i tried moving that file into the `refactoredSrc` array and I'm still getting this error.

**Comment by Miodec** [comment]
Ok i think this is the correct fix: edbc845def961172573972b21d2d41f0e78277c3. Let me know if this is not the way.

**Comment by Miodec** [comment]
Nevermind, it compiles fully, but is broken on runtime. 

image

**Comment by Miodec** [comment]
Reverted for now so i can continue working on other things

**Comment by Marco-Pagani** [comment]
I will look into this further and let you know if I can find out what's going on. It built fine for me when I made the PR

**Pull request merged**
