### PR TITLE
Communism Theme

### PR DESCRIPTION
**Pull request by Cole320**
Added a simple yellow and red classic communist theme.
image

### CODE REVIEW

**Comment by Miodec** [comment]
I dont think i like the name of this one. Plus I would tone down the saturation of the red so it doesn't hurt the eyes as much.

**Comment by UnrealApex** [comment]
I would agree, make it a bit less saturated.

**Comment by Brachyurus** [comment]
I'd definitelly use this theme If I ever wanted to learn cyrillic alphabet.

**Comment by Miodec** [comment]
> How about "Our Theme"?

Haha yeah thats a good one

**Comment by Miodec** [comment]
Ill make the changes myself.

**Pull request merged**
