### PR TITLE
add international english 1k and 10k language variations

### PR DESCRIPTION
**Pull request by setek**
Added international english 1k and 10k languages, updated _list.json with the two new files.

### CODE REVIEW

**Comment by Miodec** [comment]
Whats the difference between normal and international?

**Comment by setek** [comment]
> Whats the difference between normal and international?

We spell things differently, for instance:

OUR: neighbour - neighbor, colour - color
SE: analyse - analyze, atomise - atomize
LL: travelling - traveling, jewellery - jewelry

**Comment by Miodec** [comment]
I think a better way of going about this would be to compile a list of words that are spelled differently and add a switch to the settings that replace that word if it comes up in the generation.

**Comment by setek** [comment]
> I think a better way of going about this would be to compile a list of words that are spelled differently and add a switch to the settings that replace that word if it comes up in the generation.

That sounds good! I can uh, provide the changelist:

[intl-us-eng-changelist.txt](https://github.com/Miodec/monkeytype/files/5992414/intl-us-eng-changelist.txt)

I'm not sure I can make the changes myself though …

**Comment by Ahmad-A0** [comment]
I think the international version of the english_450k file should also be included.

[english_450k_international.txt](https://github.com/Miodec/monkeytype/files/6016217/english_450k_international.txt)
[changed.txt](https://github.com/Miodec/monkeytype/files/6016230/changed.txt)

**The files are in JSON format but JSON file upload is not supported by GitHub**

**Comment by Miodec** [comment]
Added lazy mode which does the same thing without adding a new list

**Pull request closed without merging**
