### PR TITLE
adding Everblush colorscheme

### PR DESCRIPTION
**Pull request by Mangeshrex**
I am adding the colorscheme [Everblush](https://github.com/Everblush) for its user's and myself. 

Tue Mar 22 01:09:47 PM IST 2022

### CODE REVIEW

**Comment by Bruception** [comment]
Please add more screenshots with the other settings enabled.

**Comment by Miodec** [comment]
I think this looks very simmilar to `terror below`

**Comment by Mangeshrex** [comment]
> I think this looks very similar to `terror below`

so it isn't acceptable ?

**Comment by Mangeshrex** [comment]
Wed Mar 23 08:14:03 AM IST 2022

The vscode theme also you can find this theme on nvchad its totally mine and I have handpicked all the colors

**Comment by Miodec** [comment]
> so it isn't acceptable ? I dont think so that the theme is similar to that its actually very different the bg differs a bit and the foreground colors differ a lot.

Im afraid so. Sorry.

**Comment by Ferotiq** [comment]
It does look similar to terror below imo.

**Pull request closed without merging**
