### PR TITLE
Added Discord Link Preview Image

### PR DESCRIPTION
**Pull request by teddinotteddy**

### CODE REVIEW

**Comment by Miodec** [comment]
Discord is already using the Twitter image for previews. Are you not seeing this on your machine?

**Comment by teddinotteddy** [comment]
@Miodec Yeah I'm not seeing it here. I'm using a MacBook Mid 2020 13" model with MacOS Monterey 12.1 Beta.

**Comment by Miodec** [comment]
Oh well. Then please change the url to use the social image, just like the twitter image.

**Comment by teddinotteddy** [comment]
@Miodec made those changes.

**Review by Miodec — APPROVED** [review]
Thanks

**Pull request merged**
