### PR TITLE
fix GitHub spelling on about page

### PR DESCRIPTION
**Pull request by Odyssey346**
Signed-off-by: Oxygemo <alej0hio2007@gmail.com>

### Description
On the About page, GitHub is displayed as Github. This is a common spelling mistake, so I fixed it.

### Checklist 
- [x] I have read the [`CODE_OF_CONDUCT.md`](https://github.com/Miodec/monkeytype/blob/master/CODE_OF_CONDUCT.md) and the [`CONTRIBUTING.md`](https://github.com/Miodec/monkeytype/blob/master/CONTRIBUTING.md)
- [x] I checked if my PR has any bugs or other issues that could reduce the stability of the project
- [x] I understand that the maintainer has the right to reject my contribution and it may not get accepted.

Resolves #

### CODE REVIEW

**Review by UnrealApex — APPROVED** [review]

**Comment by UnrealApex** [comment]
note: I don't have write access to this repository so you will need an approving review from Miodec to get this PR merged.

**Comment by Odyssey346** [comment]
I know, it says you're a contributor, and if you had write access, it would say Collaborator.

**Review by kikorp78 — APPROVED** [review]
Yeah, I think this should be merged but it's not that big of an error, right?

**Comment by Odyssey346** [comment]
it isn't a big issue but it'll make it more consistent with other parts of the site, like the footer.

**Review by Miodec — APPROVED** [review]

**Pull request merged**
