### PR TITLE
Add Seafoam Theme

### PR DESCRIPTION
**Pull request by teddinotteddy**
Added a seafoam theme
Screen Shot 2022-02-09 at 6 40 11 PM
Screen Shot 2022-02-09 at 6 40 27 PM

### CODE REVIEW

**Comment by Miodec** [comment]
Doesnt look like seafoam to me. More like mint icecream with chocolate chips.

**Comment by teddinotteddy** [comment]
Should I make the color lighter or rename it to mint chocolate?

**Comment by teddinotteddy** [comment]
Screen Shot 2022-02-10 at 10 40 03 AM
Screen Shot 2022-02-10 at 10 39 57 AM
Does this look better? I need a minute to change the code though.

**Comment by teddinotteddy** [comment]
Alright changed it to the new look.

**Comment by teddinotteddy** [comment]
imo the menthol theme looks much darker than seafoam.

**Comment by ryujinscales** [comment]
> Doesnt look like seafoam to me. More like mint icecream with chocolate chips.

🤣🤣

**Comment by ryujinscales** [comment]
how about `#00FFEC`

**Comment by ryujinscales** [comment]
> how about `#00FFEC`

kinda looks like `frozen llama` though

**Comment by Miodec** [comment]
> imo the menthol theme looks much darker than seafoam.

I still feel its too similar to merge

**Pull request closed without merging**
