### PR TITLE
added indonesian_2k.json

### PR DESCRIPTION
**Pull request by Ameeeek**
### Description

#

### CODE REVIEW

**Comment by Miodec** [comment]
What about #2750?

This pr also pushes the default list above 200 words.

**Comment by Ameeeek** [comment]
oh, I added a new file with 2k words inside, should I just close the other pull request?

**Comment by Miodec** [comment]
> oh, I added a new file with 2k words inside, should I just close the other pull request?

This pr also edits `indonesian.json`, pushing it to 400 words.

**Comment by Ameeeek** [comment]
oh, my bad didn't realize that i'll fix it

**Comment by Ameeeek** [comment]
sorry but can i just close #2750 PR and use this PR instead?

**Comment by Miodec** [comment]
> sorry but can i just close #2750 PR and use this PR instead?

Yeah, just closed that one

**Comment by rizwanmustafa** [comment]
So @Ameeeek What is the status of this PR?

**Comment by sumduck** [comment]
guess what?

**Comment by sumduck** [comment]
chicken byutt

**Comment by Miodec** [comment]
Closing due to inactivity

**Pull request closed without merging**
