### PR TITLE
Create horizon.css

### PR DESCRIPTION
**Pull request by Tawtis**
image
my favourite theme for vscode :)
would be awesome if we could have it in monkeytype

### CODE REVIEW

**Comment by Tawtis** [comment]
hold off on pushing this, i will edit it tomorrow morning

**Comment by Tawtis** [comment]
changes complete

**Comment by Miodec** [comment]
Make sure to update `list.json`

**Comment by Miodec** [comment]
Ill just do it for you - don't forget next time ;)

**Comment by Tawtis** [comment]
Sorry I thought I did it, mb

**Pull request merged**
