### PR TITLE
Make default timer color "main" and full opacity

### PR DESCRIPTION
**Pull request by SeerLite**
So it looks better by default with most theme. With some themes the default
black+0.25 was really hard to see, or just looked really bad.

An alternative way of doing this would be to make the timer color part of the theme, so each theme chooses what color it should use (and then some can keep the default black+0.25 if it looks better)

## serika dark (default)
image
image

## terra
image
image

## matrix
image
image

## 80s after dark
image
image

## arch
image
image

### CODE REVIEW

**Comment by Miodec** [comment]
I actually think opacity 1 would look nicer with timer color main.

**Comment by SeerLite** [comment]
I agree that with 1.0 on most themes it looks fine, but I feel like it looks too excessive/saturated with the default serika dark theme:
image
(maybe it's just me though haha. go ahead and merge if it looks fine to you)

What do you think about 0.75?
image

**Comment by Miodec** [comment]
Probably feels like this because of the big numbers. What if we make mini style the default, and then opacity 1?

**Comment by SeerLite** [comment]
Yeah I how that looks! Updated it
image

**Comment by SeerLite** [comment]
Whoops, forgot to clear and check that :s sorry
Thanks for merging

**Pull request merged**
