### PR TITLE
Add platform specific lint script

### PR DESCRIPTION
**Pull request by Ferotiq**
### Description

Added run-script-os and a platform specific lint script so that git committing with command prompt works properly.

(This has not been tested)

### CODE REVIEW

**Comment by Miodec** [comment]
> (This has not been tested)

How can we test it?

**Comment by Ferotiq** [comment]
I’ll make a commit to this branch with some dummy whitespace change or something when I get home.

**Comment by Miodec** [comment]
Getting this:
```sh
monkeytype > npm run lint

> monkeytype@1.5.6 lint
> run-script-os

sh: run-script-os: command not found
```

**Comment by Ferotiq** [comment]
try changing it to npx run-script-os

**Comment by Ferotiq** [comment]
Bruh, closing.

**Pull request closed without merging**
