### PR TITLE
Added better 512px icon!

### PR DESCRIPTION
**Pull request by Estebene**
Added better 512px icon for pwa
Untitled-3
a.

### CODE REVIEW

**Comment by Miodec** [comment]
Wait, what is this used for?

**Comment by lukew3** [comment]
@Miodec I requested a better 512x512 icon in #2142. Progressive web apps need to have an icon of this size for users to see on after it is added to their home screen.

**Comment by Miodec** [comment]
Oh, alright.

**Comment by Miodec** [comment]
Now that i look at it i probably shouldve merged the other pr first haha

**Pull request merged**
