### PR TITLE
Updated README Links

### PR DESCRIPTION
**Pull request by UnrealApex**

### CODE REVIEW

**Comment by Miodec** [comment]
Maybe `create a discussion thread` linking to `https://github.com/Miodec/monkeytype/discussions`

**Comment by Miodec** [comment]
Also should update the discord link to `https://www.discord.gg/monkeytype`

**Comment by UnrealApex** [comment]
Shall I also add a link to the issues page ?

**Comment by Miodec** [comment]
Yeah

**Comment by UnrealApex** [comment]
I added it, looks alright ?

**Pull request merged**
