### PR TITLE
Leaderboard is responsive now

### PR DESCRIPTION
**Pull request by rockingrohit9639**
### Description
Previously on monkeytype, the leaderboard was not responsive at all. 

Resolves #
I did some changes in style.scss and media-queries.scss and made the leaderboard responsive. 
Issue that can be reference is #1696 

#### After
- Desktop
image

- Mobile
image

#### Before
image

### CODE REVIEW

**Comment by Miodec** [comment]
Thanks! Couple issues i found:

Screenshot 2021-08-02 at 14 05 23
Screenshot 2021-08-02 at 14 04 59

**Comment by rockingrohit9639** [comment]
> Thanks! Couple issues i found:
> 
> Screenshot 2021-08-02 at 14 05 23
> 
> Screenshot 2021-08-02 at 14 04 59

Okay, I will fix this.

**Comment by rockingrohit9639** [comment]
@Miodec is it fine to have two vertical scrollbars on the leaderboard modal or should I hide the outer one?

image

**Comment by Miodec** [comment]
Its fine

**Comment by rockingrohit9639** [comment]
> Its fine

Okay, I have made those changes please have a loot at it.

**Review by marsbearmc — APPROVED** [review]

**Comment by Miodec** [comment]
@marsbearmc did you approve this without checking it on a local server? Because its not ready yet.

Found some more problems:
- Leaderboards text is huge
- buttons are touching each other 
- buttons are too small (please check the live version)
image

**Comment by rockingrohit9639** [comment]
> @marsbearmc did you approve this without checking it on a local server? Because its not ready yet.
> 
> Found some more problems:
> 
> * Leaderboards text is huge
> * buttons are touching each other
> * buttons are away from the right side
> * buttons are too small (please check the live version)
>   image

I am sorry about that, It is fixed now.

**Review by Miodec — APPROVED** [review]

**Comment by BuddyBob** [comment]
beautiful!

**Pull request merged**
