### PR TITLE
Adding Kurdish Language

### PR DESCRIPTION
**Pull request by taboov**
## Adding Kurdish Language
This file contain 200 words of central Kurdish. 

About [Kurdish language](https://en.wikipedia.org/wiki/Kurdish_languages). More specific about this dialect [Central_Kurdish](https://en.wikipedia.org/wiki/Sorani)

Let me know if anything wasn't clear.

### CODE REVIEW

**Review by Miodec — CHANGES_REQUESTED** [review]
Please rename to `kurdish_central`. I think there is some code somewhere that splits the language on `_` and takes the first part which wouldn't work with the current name.

**Comment by taboov** [comment]
Central_Kurdish also called "Sorani" if you think one word is better and solve the problem, I can rename them to `sorani`.

**Comment by Miodec** [comment]
> Central_Kurdish also called "Sorani" if you think one word is better and solve the problem, I can rename them to `sorani`.

Yeah lets go with that

**Review by Miodec — APPROVED** [review]

**Comment by roj1512** [comment]
@taboov "Sorani" is not a standard.

**Pull request merged**
