### PR TITLE
Separate backend and frontend dependencies

### PR DESCRIPTION
**Pull request by Bruception**
### Description

- Separated the dependencies of the frontend and backend.
- This seems to have improved frontend build times.
- I recommend checking out the project structure through here: https://github.com/Miodec/monkeytype/tree/bruce

### CODE REVIEW

**Comment by CameronCT** [comment]
I think separating is a great idea as mentioned in Discord before. Introducing TypeScript could easily increase build times by an extra 2-4 seconds (based off my experience) so this is a step forward.

PR looks good so far / seems to work for me. I was worried that maybe you wouldn't have separated the ESLint properly but that's also all good.

**Comment by Miodec** [comment]
> I think separating is a great idea as mentioned in Discord before. Introducing TypeScript could easily increase build times by an extra 2-4 seconds (based off my experience) so this is a step forward.
> 
> PR looks good so far / seems to work for me. I was worried that maybe you wouldn't have separated the ESLint properly but that's also all good.
> 
> To add to this: It might be still worth adding `start:dev:nodb` and `start:dev:nofe` to the main `package.json` file.
> 
> ```js
>     "build": "npx gulp build",
>     "start:dev": "npm run build && concurrently --kill-others \"npx gulp watch\" \"nodemon --watch ./backend ./backend/server.js\" \"firebase serve --only hosting\"",
>     "start:dev:nodb": "npm run build && concurrently --kill-others \"npx gulp watch\" \"firebase serve --only hosting\"",
>     "start:dev:nofe": "nodemon --watch ./backend ./backend/server.js",
>     "deploy:live": "npm run build && firebase deploy -P live --only hosting"
> ```

Yeap, seems weird that you now have to manually start up the frontend and backend when working on both.

**Comment by Bruception** [comment]
> > I think separating is a great idea as mentioned in Discord before. Introducing TypeScript could easily increase build times by an extra 2-4 seconds (based off my experience) so this is a step forward.
> > PR looks good so far / seems to work for me. I was worried that maybe you wouldn't have separated the ESLint properly but that's also all good.
> > To add to this: It might be still worth adding `start:dev:nodb` and `start:dev:nofe` to the main `package.json` file.
> > ```js
> >     "build": "npx gulp build",
> >     "start:dev": "npm run build && concurrently --kill-others \"npx gulp watch\" \"nodemon --watch ./backend ./backend/server.js\" \"firebase serve --only hosting\"",
> >     "start:dev:nodb": "npm run build && concurrently --kill-others \"npx gulp watch\" \"firebase serve --only hosting\"",
> >     "start:dev:nofe": "nodemon --watch ./backend ./backend/server.js",
> >     "deploy:live": "npm run build && firebase deploy -P live --only hosting"
> > ```
> 
> Yeap, seems weird that you now have to manually start up the frontend and backend when working on both.

I added a `start:dev` script to the root directory that will start both.

**Review by Miodec — APPROVED** [review]
Thanks

**Pull request merged**
