### PR TITLE
Add Sewing Tin themes

### PR DESCRIPTION
**Pull request by minicap-cat**
### Description

Adds light and dark Sewing Tin themes, based on the [KAM Sewing Tin](https://geekhack.org/index.php?topic=112929.0) keyset.

Screenshot of light theme:
Screen Shot 2021-09-18 at 8 35 22 PM

Screenshot of dark theme:

Screen Shot 2021-09-19 at 3 07 44 PM

### CODE REVIEW

**Comment by Miodec** [comment]
I removed the light theme because its similar to other themes available, but ill merge in the dark one.

**Comment by minicap-cat** [comment]
@Miodec thanks for the review! Which theme was the light theme too similar to? I checked the other themes with a white background (Magic Girl, Milkshake, Ms Cupcake) and none of them have the blurple/yellow combination. 

Screen Shot 2021-09-20 at 1 38 05 PM
Screen Shot 2021-09-20 at 1 37 49 PM
Screen Shot 2021-09-20 at 1 37 40 PM

I'm quite fond of the gradient monkeytype logo in the light theme - I think it's a unique touch that represents the set well, but I wasn't able to find a good way to incorporate the gradient in the dark theme. I was also hoping to be able to use the light theme myself. Totally understand that you don't want to have similar themes though!

**Comment by Miodec** [comment]
Well i initally thought milkshake was going to be similar, but actually - ill add it.

**Comment by minicap-cat** [comment]
Awesome, thank you!

**Pull request merged**
