### PR TITLE
command line addition

### PR DESCRIPTION
**Pull request by aNOOBisTheGod**
Here is the addition of 1 line of code that will help people who type like not really good search something in command line. Like before when they were typing "ive" in the command line there were 0 results and now there are reults with words "live"(cause it contains "ive") inside them like "live WPM..." and so on
I guess that will not really abuse website cause I've tested this on my pc and it worked quite well

### CODE REVIEW

**Comment by ryujinscales** [comment]
> Here is the addition of 1 line of code that will help people who type like not really good search something in command line. Like before when they were typing "ive" in the command line there were 0 results and now there are reults with words "live"(cause it contains "ive") inside them like "live WPM..." and so on I guess that will not really abuse website cause I've tested this on my pc and it worked quite well

i wanted to know how u tested it
i want to test my gradient theme

**Comment by ryujinscales** [comment]
> Here is the addition of 1 line of code that will help people who type like not really good search something in command line. Like before when they were typing "ive" in the command line there were 0 results and now there are reults with words "live"(cause it contains "ive") inside them like "live WPM..." and so on I guess that will not really abuse website cause I've tested this on my pc and it worked quite well

i think u downloaded source code

**Comment by ryujinscales** [comment]
but for me css is not working

**Comment by rizwanmustafa** [comment]
> but for me css is not working

You need to fork this repo and follow the instructions in the CONTRIBUTING.md

**Comment by ryujinscales** [comment]
> > but for me css is not working
> 
> You need to fork this repo and follow the instructions in the CONTRIBUTING.md

ive done that

**Comment by ryujinscales** [comment]
> > > but for me css is not working
> > 
> > 
> > You need to fork this repo and follow the instructions in the CONTRIBUTING.md
> 
> ive done that

only problem is i wnat to preview a gradient theme im planning to create

**Comment by rizwanmustafa** [comment]
> > > > but for me css is not working
> > > 
> > > 
> > > You need to fork this repo and follow the instructions in the CONTRIBUTING.md
> > 
> > ive done that
> 
> only problem is i wnat to preview a gradient theme im planning to create
> 

You can either use custom themes in the monkeytype website or if you are using raw css, you need to place the css in the development build. If you have any problems while setting up the development build, you can contact me.

**Comment by ryujinscales** [comment]
> > > > > but for me css is not working
> > > > 
> > > > 
> > > > You need to fork this repo and follow the instructions in the CONTRIBUTING.md
> > > 
> > > 
> > > ive done that
> > 
> > 
> > only problem is i wnat to preview a gradient theme im planning to create
> 
> You can either use custom themes in the monkeytype website or if you are using raw css, you need to place the css in the development build. If you have any problems while setting up the development build, you can contact me.

I wanna know how to from step 1 pls

**Pull request closed without merging**
