### PR TITLE
Rewrite input system to use <input> content

### LINKED ISSUE #36: Can't type accented characters
I'm having trouble using accented characters like á, é, í, etc in spanish. Those characters need two keys to be pressed to be registered, first the accent and then the letter. If I try to do that nothing happens, it's like those keystrokes are not been registered.

### LINKED ISSUE #531: Linux input issues / Dead keys not working
Taking the test with french, words with ^ are not registered
Can't type êôî…
Using a custom keyboard with a bépo layout and Linux, but these points shouldn't be a problem

### LINKED ISSUE #1297: Keys that insert two characters with one press do not work [Arabic]
Keys that insert two characters at the same time do not work

In Arabic, there are certain keys that do so.

**To Reproduce**

1. Go to Add Arabic layout
2. Try to press any of those keys
1000px-KB_Arabic svg 2

**Expected behavior**
Those characters to be typed

**Current behavior**
Input being ignored

**Desktop:** 
 - OS: Windows 10
 - Browser  Chrome
 - Version 90.0.4430.85

### LINKED ISSUE #1403: Characters how need a SHIFT " to make ö, ü or ä suddenly not working anymore. [GERMAN]
1. 'I work on an english Keyboard. I have to press " + a to make the character ä ( or ü ö) '
2. As soon as I press " it shows up as an Typo, but normally it waits for the second key

After Log out and Login again, it works. But I have to restart allways.

Thanks

### LINKED ISSUE #1902: Unable to use actual layout of OS
App allows to switch to CZ language. However if I use my own layout or official layout, symbols I'm supposed to type (č,ž, í …) are not typable, because I think the app reads scancodes or smth like that, not actual symbols typed.

I understand that this is primarily ENG app, but if it offers different languages, there should be way how to use it. Simple solution could be to turn off interpreting scancodes (or smth like that) and actually using what OS think it was typed.

### PR DESCRIPTION
**Pull request by SeerLite**
[Preview page](https://seerlite.github.io/monkeytype/issue/531-input-rewrite/)

Fixes #531
Fixes #36
Fixes #1297
Fixes #1403
Fixes #1902

Also I'm pretty sure this should be enough in order to start working on an input mode for "grouped character" languages.

As always feel free to request any changes you feel necessary and just ask if there's anything unclear/confusing.

### CODE REVIEW

**Comment by Miodec** [comment]
And #1297

**Comment by Miodec** [comment]
And #1278 
And #811

**Comment by Miodec** [comment]
Is this fully done? Was this tested with dead keys and extreme cases like korean?

**Comment by SeerLite** [comment]
No, it doesn't work with the multi-keypress-character languages yet! It only fixes #531 and #36.

The issue with those is that it's hard to know when a character is "complete" or still "typing". The IBus fix in this PR matches against known diacritics only.

**Comment by SeerLite** [comment]
We could maintain a list of composed characters for each language and handle those the way diacritics are handled here. Though we wouldn't be able to know if a character is being correctly typed while it isn't "complete" yet, so the check would only happen once it's "commited".

It'd be useful to see how other typing tests handle these languages, maybe it isn't as complicated

**Comment by Miodec** [comment]
Im thinking because if i were to rewrite the input i would completely go away form storing the input in a variable and just reading the input box / text area value. 

Like, how difficult would it be to upgrade it once more to support the 'composed characters'

**Comment by thiagomeireless** [comment]
Hey guys, I found a bug when using the `Restart Button` feature:

- If I click the button to trigger the restart, everything works fine
- If I use the TAB -> ENTER shortcut to focus and press the button, the first letter of the new test is always wrong

Here's a video showing it, where I click the button in the first tests and then use TAB -> ENTER to trigger the error

https://user-images.githubusercontent.com/6698296/116768188-1d6d5a00-aa0b-11eb-92a4-3b9b78481b27.mp4

**Comment by SeerLite** [comment]
I've updated the preview page with the latest changes.

@thiagomeireless Hey! Sorry for not answering before :: The new changes should fix those problems too. Could you check it out again?

**Comment by SeerLite** [comment]
Alright, _now_ it should work on both Chromium and Firefox :)

**Comment by thiagomeireless** [comment]
Hey @SeerLite no worries :)

Thank you for all the hard work! Tested Portuguese language with all accents/dead keys on Firefox, Chrome and Chromium with success! The 'restart' button with hotkeys also worked perfectly. I'm on Ubuntu btw if it matters.

**Comment by PAHXO** [comment]
Tested on Arabic and even Arabic([Lulua](https://github.com/PromyLOPh/lulua)) layout works great!

**Comment by PAHXO** [comment]
https://en.m.wikipedia.org/wiki/Unicode_equivalence#Normalization

https://withblue.ink/2019/03/11/why-you-need-to-normalize-unicode-strings.html

A test text word if it was an a composed form sometimes are broken.

Proper normalization of the unicode is needed. Also, checking if last typed char has a (combining class) value of 1.

Additionally, you probably need to compare all the previous chars of both words(test word and the current word being typed) each time the user types an input since:-

''Unicode strings cannot be compared on the character or even byte level. UTS #10 defines the Unicode Collation Algorithm, which should be used to correctly sort (and compare, which is the same thing) Unicode strings. Step 1.1 explicitly mentions that before doing anything else both strings must be normalized into form D (which stands for decomposed)."

**Comment by SeerLite** [comment]
> A test text word if it was in a composed form sometimes are broken. (Probably can be easily fixed by normalizing the text into a (decomposed form) first before starting the test)

Yeah that's right, but I thought it'd be better to normalize it into a composed form instead. Why decomposed form? Currently all input is normalized constantly in NFC form (so decompose and re compose).

>Proper normalization of the unicode is needed. Also, checking if last typed char has a (combining class) value of 1.
>
>Additionally, you probably need to compare all the previous chars of both words(test word and the current word being typed) each time the user types an input since:-
[...]
*Probably we wouldn't need to compare all the previous chars of a word. We should probably do it to last char which has a (combining class) value of 0

I think I'm missing some key details on how the Arabic input works because I'm not understanding this. This PR was mostly for diacritics in the Spanish and Portuguese language. Are most characters in Arabic in the composed form, or are there a big amount of "diacritic"-like characters? Does the input get inserted as you type the characters do they act like dead keys and get delayed until a "final" character or a space?

I think I could use a short video about how the input system works to understand haha.

**Comment by uqs** [comment]
I'm also affected by this input issue, but it looks like the preview doesn't fully fix it.

Setup is Chrome 90 on Linux. I'm using the "us" keyboard with a compose key (`setxkbmap -option ctrl:nocaps -option compose:ralt` which is a sane way to get dead keys). To enter umlauts, I thus need to press right Alt, then ", then a to result in ä. This also works under ChromeOS with the "US EXTD" layout and there are layouts for Windows that do the same.

Due to a change in input methods years ago, hitting right Alt will (depending on the program) display a visual character and then combine the input characters.

The current live version totally ignores this composing, the preview version smears the three keypresses into three chars, with the last one being ä or ö indeed, but it's not recognized as a correct entry.

The good news: Firefox + preview version works perfectly, so this is down to being a bug with Chrome

**Comment by SeerLite** [comment]
@uqs Thank you. I pushed an update for the Compose key on IBus. It should work on both Chromium and Firefox now :)
Does it work on your end?

**Comment by uqs** [comment]
Thank you! I can confirm that this now works under *nix in both Firefox and Chrome.

Note however that it's only partially working under ChromeOS with the "US EXTD" keymap. There, the single combinations like Alt+q will produce ä just fine, but the arbitrary combining of glyphs using dead keys doesn't. That is Alt+" followed by any of a/u/o/e will produce only the last char, not the combination.

I never type test from a ChromeOS device, so I don't really care much, but I figured to test it anyway.

I can probably test Windows also later today.

**Comment by SeerLite** [comment]
Unfortunately I don't have a ChromeOS device and I don't know how to emulate a similar enough setup to test the input. Would you mind sending me some debug info? Maybe it's an easy fix.
It'd be:
1. Open the dev tools (e.g. with Ctrl + Shift + I)
2. Go to the Console tab
3. Paste in:
```javascript
$("#wordsInput").css("opacity", 1).css("position", "static").on("input", event => console.log(JSON.stringify(event.target.value), JSON.stringify([...event.target.value].map(char => char.codePointAt(0)))))
```
4. Type in the characters that don't work correctly into the test.

As you type check for any difference between the test and the content of the white input box above. Also copy or take a screenshot of the relevant output on the Console (like when you just typed the characters). If you can, a video of all this would be nice but it's not necessary.

**Comment by uqs** [comment]
Uhh, did you fix it some other way in the meantime? Because it's working fine under ChromeOS now as well, both with the "direct" keycodes, as well as the combining (which produces just 1 event, apparently)

Debug output looks roughly like so:

```
monkeytype.js:4240 loading localStorage config
monkeytype.js:7193 getting language json
/monkeytype/issue/531-input-rewrite/images/fav.png:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load SourceMap: Could not load content for https://seerlite.github.io/monkeytype/issue/531-input-rewrite/js/moment.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
$("#wordsInput").css("opacity", 1).css("position", "static").on("input", event => console.log(JSON.stringify(event.target.value), JSON.stringify([...event.target.value].map(char => char.codePointAt(0)))))

S.fn.init [textarea#wordsInput]
VM24:1 " h" [32,104]
VM24:1 " he" [32,104,101]
VM24:1 " her" [32,104,101,114]
VM24:1 " here" [32,104,101,114,101]
VM24:1 " hereä" [32,104,101,114,101,228]
VM24:1 " here" [32,104,101,114,101]
VM24:1 " her" [32,104,101,114]
VM24:1 " he" [32,104,101]
VM24:1 " h" [32,104]
VM24:1 " " [32]
VM24:1 " ä" [32,228]
VM24:1 " ää" [32,228,228]
VM24:1 " äää" [32,228,228,228]
VM24:1 " ääää" [32,228,228,228,228]
VM24:1 " äää" [32,228,228,228]
VM24:1 " ää" [32,228,228]
VM24:1 " ä" [32,228]
VM24:1 " " [32]
VM24:1 " h" [32,104]
VM24:1 " he" [32,104,101]
VM24:1 " heh" [32,104,101,104]
VM24:1 " hehr" [32,104,101,104,114]
VM24:1 " hehrä" [32,104,101,104,114,228]
```

I've never had monkeytype open on the ChromeOS device before, so I do _not_ think my test yesterday ran into some bad caching issues.

**Comment by SeerLite** [comment]
Hah well that's weird! I haven't updated it from last time.
> I've never had monkeytype open on the ChromeOS device before, so I do not think my test yesterday ran into some bad caching issues.

Didn't you test ChromeOS when first reporting the issue though? :

Still, I just looked up what ChromeOS uses for input and it should be using IBus too, so it should work just like the mainstream Linux distros/DEs. That means there should be more than a single input event to produce the characters with dead keys (unlike the output you posted).

Maybe something failed when booting and IBus didn't start? Or it got closed accidentally? Could you reboot a few times and check if anything changes?

If it's working correctly then we can move on and just blame it on some weird caching issue or maybe something funky happening with github pages ;)

**Comment by uqs** [comment]
Hmm, I've concluded that I must've done my previous ChromeOS test with the live version, not the preview version. My browser history seems to confirm that as well. Oops.

So, the _preview_ is fixing ChromeOS as well, the live version is still busted, of course. Sorry for the confusion.

Ship it! :)

**Comment by SeerLite** [comment]
@Miodec This should be ready to merge. I couldn't get mobile input to work 100% of the time because every keyboard/browser I tried did something different with selections and stuff. For now at least this should work on most cases on PC.

### Summary of how the input works now
`TestLogic.input.currentWord` is bound to the contents of `$("#wordsInput")`. Any changes to it will reflect on the input element and vice-versa.

Inside `input-controller`, in the `$("#wordsInput").on("input")` event, only if the content of the input is larger than before, the last character is handled (accuracy calculated, check if it's space, etc).

`Misc.trailingComposeChars` is a regex that tries to match most of the compose/diacritic characters at the end of the string. This one is used to decide whether or not to calculate the accuracy and also the rendering of it. This is for IBus input which inserts a temporary character of this kind when pressing a dead or compose key.

---
Looking back now I feel like it's a bit messy but I don't know how to make it cleaner. I hope it's readable and easy enough to understand. If not feel free to request any changes or ask how something works or why it's there

Also I think the changes to the files in static/ were done by the auto-formatter when merging with master :s I think ideally prettier should be run everytime a PR is merged considering some people adding quotes and languages are using the GitHub UI instead of `git`

**Comment by Miodec** [comment]
@SeerLite prettier runs automatically on each commit

**Comment by Miodec** [comment]
Is your preview page up to date? I wanna test this with people as much as possible.

**Comment by SeerLite** [comment]
> Nevermind i see what you mean. Yeah i dont know why the languages were not prettified already.

I think it's because the GitHub UI only adds the files and doesn't run the hooks. I don't know if it's possible to make it run them

The preview page should be up to date. Also merged master to it now

**Comment by Miodec** [comment]
Some people are reporting the test is starting in the middle of the first word 
image
and then it counts it as wrong no matter what they type

**Comment by Miodec** [comment]
I reproduced the above issue by pressing space a lot of times while the test is restarting. (so tab > space space space space space space space space)

**Comment by SeerLite** [comment]
I see what's going on. I fixed it when restarting, but it still happens when pressing keys while the page is loading if the "no focus" warning is disabled.

I thought I was being really smart by separating the keydown event into one for the document and one for the input. Turns out it breaks some stuff related to autofocus when the warning is disabled.

I'll see what I can do to fix it, maybe I end up reverting it to a single event.

**Comment by SeerLite** [comment]
Should work all fine now!

**Comment by iuuang** [comment]
https://user-images.githubusercontent.com/85116541/120200614-d3071500-c224-11eb-9a70-da504c3d9fad.mp4

**Comment by SeerLite** [comment]
@iuuang What device is it?

**Comment by Miodec** [comment]
> @iuuang What device is it?

Looks to be an iPad Pro

**Comment by iuuang** [comment]
yeah is an iPad pro running IpadOS but now that I try it on mac using vivaldi (chromium) it works fine for some reason. 
With the current input system there is a problem is spanish where if you hit "´" and then backspaced it would erase two characters insted of just cancelling the "´" input.
Also this system now works with chinese and japanese, only on desktop, bc when I tried it on ipadOS it repeats the input too for some reason. 
Conclusion: works on desktop but not on iPadOS. I still need to try android to see if I can finally input something there.

**Comment by iuuang** [comment]
oke, now I can input things on android and punctuation seems to work fine aswell as typing chinese and japanese altough it behaves a bit strange in those two bc it seems like its switching between being in a input satate and not very fast when using backspace.

**Comment by iuuang** [comment]
Nvm it just lets you input the characters but then the result counts the characters that you wrote to get that input, so no, it doesn't really work 100% with chinese, japanese or other languages that requiere you input something to get a different output. I think this doesn't happen in android because it doesn't realease the characters but it registers it until you select an output. 
https://streamable.com/z5dbdb

**Comment by SeerLite** [comment]
> With the current input system there is a problem is spanish where if you hit "´" and then backspaced it would erase two characters insted of just cancelling the "´" input.

This on desktop?

For now I'm only focusing on fixing basic diacritics insertion on desktop, to get it merged soon.

On Android, each browser+keyboard combination I tried did something slightly different to insert/remove characters. I tried implementing something generic enough but it's probably broken in most common cases anyway. Maybe something that works better can be implemented in the future.

Languages like Korean, Japanese and Chinese need extra logic to handle every stage during the insertion of each and every character (or word, depending on the input system). This is a lot of work and requires a better understanding of the input systems for these languages across different OSs.
Also the fact that Monkeytype tries to give immediate feedback for every character, and unlike other typing websites, _hides_ the real input to show its own, only make this harder.

**Comment by iuuang** [comment]
No that was on iPadOS, it is fundamentally different to the other ones because what I think its doing its that is communicating to the page that the "´" key has been pressed but to not register it somehow and then just outputs the final result. 
It works fine on desktop for all the time that I tried bc you fixed the double character delete problem when you pressed "´" and backspace in the current system. 

As for what I know about android the keyboard is universal except in a few cases and it works just fine like on desktop. 

As for what asian languages and other languages with similar input I think something could be worked out like excluding the roman char set or require input confirmation just like 10ff but I think thats a very poor implementation. The other way is just a lot of work finding open source code that lets you convert pinyin into chinese and such... I understand that this is not the priority but it would still be pretty cool to have it. 

TL,DR: works fine everywhere but on iPadOS

**Comment by SeerLite** [comment]
Power mode looks sick lol

@Miodec It should be ready again. Preview page is also up to date

**Comment by Miodec** [comment]
Did you find out what was breaking iPadOS?

**Comment by thiagomeireless** [comment]
What happened to this PR? Anything we can help as testers to make this go live?

Been using the preview page for the last two months instead of monkeytype.com lol

**Comment by SeerLite** [comment]
@thiagomeireless Sorry for the wait! I've been busy last few weeks with school. In a few days winter vacations are starting so I'll get some free time to get back to this

Time passes really fast lol it feels like it was just 3 days ago I was working on this and now suddenly it's been a whole month

**Comment by Miodec** [comment]
> This leaves a weird outline around the screen along with a square in the top left. Please fix it

Not related to this PR. Just a small bug I introduced.

**Comment by SeerLite** [comment]
@Miodec their comment seems to be on your commit, not the PR. Looks like I messed something up here and now commits from master (and their comments) are showing. Not sure why it happened, I merged just like I was doing previously. Trying to fix it right now

**Comment by Miodec** [comment]
> their comment seems to be on your commit, not the PR.

Hm, weird.

**Comment by thiagomeireless** [comment]
I'm not sure if you want random reports like this, but last commits introduced a bug for me:

When pressing Tab + Enter to reset the test, the page just hangs, like there's an infinite loop, and I must close the tab and open a new one to do a new test.

This happens only on Chrome, Firefox is fine.

**Comment by SeerLite** [comment]
I realized all the noise autoformatting diffs from unrelated files all came from the merge commits, so I went through all of them and worked around it by disabling the hook altogether, to get a more realistic final diff. Now it's actually readable :)

Also learned recently that to it's better practice to rebase instead of merge from master when syncing a PR, so that's what I'll be doing in my future PRs.

Apart from that I fixed some bugs that I didn't notice before, including Chrome hanging @thiagomeireless Thank you for reporting that one, I always forget to test Chrome. And yeah reports here are welcome!

Now I just need to fix a small bug with swipe/instant input and also debug that problem on iOS(?) that I've been delaying hehe. After that, this should be ready

**Comment by iuuang** [comment]
https://user-images.githubusercontent.com/85116541/126379869-03295272-19a8-4c57-b209-7957e6914b60.MP4

Device: Ipad pro 11” 2018 
OS: iPadOS 15 developer beta 2 
So basically what I think is happening is that when I hit the ´ “dead key”; ´ appears and then waits for me to type a vowel to complete to either áéíóú but when I hit the dead key ´ and then type something that is not a vowel it writes, for example, ´w which is fine but then trying to delete that with backspace and that weird thing happens, first hit nothing happens, second hit cursor appears to reset or something (?), third hit it deletes whatever is after the ´.

**Comment by SeerLite** [comment]
Spent some time messing around with `git rebase` and rebased the whole thing. History looks a bit cleaner now.
I feel like I both learned an amazing skill and accomplished absolutely nothing at the same time. I don't regret it though, it'll probably come in really useful in the future.

Anyway, I fixed that bug @iuuang reported which actually wasn't exclusive to iPadOS, and also some new bugs I found during the rebase, e.g. with the replay (though I think the replay is still really buggy sometimes? but sometimes it's also buggy for me on the live version so idk I don't wanna mess too much with it).

**Comment by Miodec** [comment]
How's it going @SeerLite ?

**Comment by uqs** [comment]
Uh, did Chrome 92 break Monkeytype for anyone else on Linux? It sees double input characters all the time. Strangely only happens on my qmk keyboard(s), my classic keyboard is still working fine. Firefox is unaffected, as usual ... and the preview of this rewrite also is still working fine.

**Comment by uqs** [comment]
Ok, nevermind, there is a Chrome bug open for this, and the workaround for me is to _not_ set `#define USB_POLLING_INTERVAL_MS 1` in QMK. This adds about 5ms latency on average, but I think 10ms is what most keyboards use anyway.

**Comment by iuuang** [comment]
For me this is ready for prime time already, I can't find any more bugs in spanish other than OS level input errors.

**Comment by Miodec** [comment]
> Ok, nevermind, there is a Chrome bug open for this, and the workaround for me is to _not_ set `#define USB_POLLING_INTERVAL_MS 1` in QMK. This adds about 5ms latency on average, but I think 10ms is what most keyboards use anyway.

Could you link this Chrome bug?

**Comment by uqs** [comment]
I'm not sure if it is publicly visible: https://bugs.chromium.org/p/chromium/issues/detail?id=1232428

It hits me for a QMK keyboard where I set the USB polling interval to 1ms and am using a layer toggle for backspace, so in effect the backspace down/up events only get send on physical key release, which means they make it to the OS within 1ms, as can be seen by xev(1) also.

I had no luck reproducing that with xdotool, but some others can repro.

Even changing back to 10ms polling and setting TAP_CODE_DELAY to 10 doesn't fully fix it, especially when the system is loaded and Chrome is failing to keep up with events.

A fix is in the works though, not sure it'll fully fix this though ...

**Comment by SeerLite** [comment]
Sorry to keep you all waiting. I cleaned up and rewrote some parts of the rewrite so they actually make sense now and need less workarounds. Also fixed a bunch of obscure bugs I found with the previous implementation. I worked around autocorrect on mobile by making the input a password type, hopefully password managers won't try to autofill it :P

I'd appreciate it if some of you could do one last test on the [preview page](https://seerlite.github.io/monkeytype/issue/531-input-rewrite/) to make sure it's working everywhere. This time it should be ready for real :)
Thank you!

**Comment by Miodec** [comment]
I found that on Mac, ctrl or option + backspace doesn't word by word. (testing with stop on error: word on)

**Comment by uqs** [comment]
Not sure what settings are required, but ctrl-backspace deletes the last full word just fine under Linux and Chrome 92

**Comment by KNIX3** [comment]
The testing page works great for me. ctrl + backspace works fine, as do the various dead keys of bépo.
OpenBSD
X11
Bépo AFNOR

**Comment by AntoNoll** [comment]
The dead keys characters (û, ê etc...) work well for me, however the ctrl + backspace make a "Afficher les identifiants enregistrés" window (i.e. "show the saved usernames" or something) appear. This is probably related to the password trick. 
bug_monkeytype

**Comment by CrumblyLiquid** [comment]
Typing works flawlessly on Czech QWERTY layout (Firefox 91.0.2, Manjaro). No problems with dead characters or Ctrl + Backspace.

One thing I'm not sure about is that on your preview page some accented characters don't use proper font. This seems to be the case across all fonts (although with some of the it's less noticeable).

The problem seems to be with these characters: ě š č ř ž ň ť ď ů (there are more of them but these are the ones that are used in the czech language)

You can test this by selecting the 'custom' mode and using this array of character: "a b c d e | á é í ó ú ý | ě š č ř ž ň ť ď ů"
You can see that the first and second part uses the right font but the last one doesn't (parts are separated by pipes).

This is how it looks on monkeytype.com:
image
This is how it looks on the preview page:
image

Example with Lexend Deca font:
image

In the word "Manžel" the 'n' uses the Lexend Deca font (which is correct)
image
However then letter 'ž' uses DejaVu Serif font but it should use the Lexend Deca font.
image

I've noticed there are some differences in css files between monkeytype.com and the preview page. That might be the cause of that or it might have something to do with different domains and how or which fonts load.

Preview page: 
image
Monkeytype.com:
image

You can reproduce this by going to the preview page settings language to 'czech 10k' (if you want to try typing choose the Czech QWERTY layout)

**Comment by CrumblyLiquid** [comment]
Just tested it locally on my PC and couldn't replicate the issue. This is probably only problem on your preview page.

**Comment by SeerLite** [comment]
@CrumblyLiquid Sorry for taking so long to answer! Yes, it's an issue with the page, which I'm trying to host as "statically" as possible. It's completely unrelated to the PR

**Comment by CrumblyLiquid** [comment]
@SeerLite Thanks for getting back to me! I've been running a patched version locally for a while now but I would rather use monkeytype.com

Are there any plans for merging this into master anytime soon? If this needs PR any tweaking, improvements or testing I'll gladly help!

**Comment by SeerLite** [comment]
Oh, maybe I shouldn't force push when the rebase has no effects, whoops. Sorry, I did it out of habit

Anyway this was just a rebase, no changes from previous rev

**Comment by SeerLite** [comment]
@CrumblyLiquid Sorry, I missed your message again :s Yeah, this should hopefully be merged pretty soon now :)

As for help, all that's needed for now is to make sure it works correctly and doesn't break existing functionality. So just using the same configuration you might already use in monkeytype.com to make sure it works and reporting issues would be helpful. However I think you're already doing that in your local version.

So yeah, just let me know if you find any issues! Thank you

**Review by Miodec — APPROVED** [review]

**Comment by Miodec** [comment]
Yolo

**Comment by thiagomeireless** [comment]
Thank you very much for this @SeerLite !

It has been a journey watching the PR finally go live.

Thanks for merging Jack. Yolo!

**Comment by koldaman** [comment]
Seems to me, that after merging to master the Enter key is not working in Custom texts. It is always underlined as error. Do not know, if its due to this changes, or from somewhere else.
Other staff works great, thanks!

**Comment by mrzool** [comment]
Great to see this merged! Thanks @SeerLite and @Miodec

**Pull request merged**
