### PR TITLE
'Wasp' theme

### PR DESCRIPTION
**Pull request by ryujinscales**
image
above : colorful mode and flip test colors on
-----------------------------------------------------------------------------------------------------------------------------------------
image
above : normal
--------------------------------------------------------------------------------------------------------------------------------------------
image
above : flip test colors
------------------------------------------------------------------------------------------------------------------------------------------
image
above : colorful mode
-------------------------------------------------------------------------------------------------------------------------------------------
image
above : after test
------------------------------------------------------------------------------------------------------------------------------------------
image
above : afk
=================================================================================
`print("signing_off")`

### CODE REVIEW

**Comment by ryujinscales** [comment]
and forgot to mention, any idea how my  username is not visible

**Comment by ryujinscales** [comment]
and hope i solved the conflict

**Comment by Miodec** [comment]
Sorry i don't really like this one

**Comment by ryujinscales** [comment]
it's ok

**Pull request closed without merging**
