### PR TITLE
Rename scripts to ts

### PR DESCRIPTION
**Pull request by Ferotiq**
### Description

Closes #

### CODE REVIEW

**Comment by rizwanmustafa** [comment]
Please add `firebase-config.ts` to gitignore.

**Comment by Ferotiq** [comment]
it's there... I have no idea why it's going through

**Comment by Ferotiq** [comment]
now it works... wtf

**Comment by rizwanmustafa** [comment]
Remove it from gitignore. Delete it, add deletion change. Commit and then add to gitignore and then add the actual file back.

**Comment by Ferotiq** [comment]
luckily the firebase-config isn't important to release to the public

**Comment by rizwanmustafa** [comment]
Yeah

**Comment by Miodec** [comment]
Looks good, will merge after #2862

**Review by Miodec — APPROVED** [review]

**Pull request merged**
