### PR TITLE
Added moriz theme

### PR DESCRIPTION
**Pull request by rizwanmustafa**
This is going to be my first contribution, so I am really excited for it.

Normal
normal

Flipped Test Colors
flipped_test_colors

Colorful Mode
colorful_mode

### CODE REVIEW

**Comment by teddinotteddy** [comment]
The completed text color is hard to read. So I recommend changing the sub color to something that will contrast well.

**Comment by Miodec** [comment]
I think its fine, thats what the colorful and flip colors settings are for.

**Comment by Miodec** [comment]
Im gonna have to deny this one though. I think its too similar to other themes, mainly future funk. Sorry.

**Comment by rizwanmustafa** [comment]
NP.

**Pull request closed without merging**
