### PR TITLE
Pseudolang funbox mode - gibberish, but more wordlike

### PR DESCRIPTION
**Pull request by shishberg**
### Description

**NOTE:** I'm not sure whether this is a good idea. It seemed fun so I thought I'd share it, but it's totally up to you whether to do anything with it.

Generates random words using ngram distributions from the current language. The result is gibberish (I originally called it "gibberish" before I realized that was already the name of a funbox mode) but with similar patterns to real language.

Screen Shot 2021-08-15 at 2 17 14 pm
Screen Shot 2021-08-15 at 2 17 14 pm
Screen Shot 2021-08-15 at 2 17 23 pm
Screen Shot 2021-08-15 at 2 17 39 pm

### CODE REVIEW

**Comment by Miodec** [comment]
How do you actually generate this? I don't see a bigram list or anything like that

**Comment by shishberg** [comment]
> How do you actually generate this? I don't see a bigram list or anything like that

The `WordGenerator` constructor generates an ngram list from the language.

**Comment by Miodec** [comment]
How about we rename this funbox to `pseudo_lang`, `pseudolang` or `pseudo_language` - your choice.

**Comment by shishberg** [comment]
Done.

**Comment by Miodec** [comment]
Also, have you tested it past 100 words? After 100 the word generation uses the function `addWord`

**Comment by shishberg** [comment]
I think so. Let me check...
...
Yep. Tested with 200 words, seems fine.

**Review by Miodec — APPROVED** [review]

**Pull request merged**
