### PR TITLE
added theme for ePBT Fruit Chew

### PR DESCRIPTION
**Pull request by adii-n**
### Description
Added theme for ePBT Fruit Chew (added theme.css file titled fruit_chew.css and entered it into theme list)

### CODE REVIEW

**Comment by Miodec** [comment]
Please include a screenshot when adding themes

**Comment by mrbannanaman** [comment]
[screenshot](url)

**Comment by Miodec** [comment]
Honestly, i dont think it looks good at all. Aspecially the favion. Also, it doesn't really fit the keycap set either.
image
image

**Comment by mrbannanaman** [comment]
Hmm, will revisit eventually and revise

**Comment by teddinotteddy** [comment]
I agree with Miodec. It doesn't match the keycaps
7rj1duz271d71 Small

Make the background white and have the menu icons to be the different fruit colors. Make the purple less harsh. After that it should be good.

**Comment by batsoup804** [comment]
saw this and I agree with miodec as well so I made some edits. 
image
image
Here's the base stuff, feel free to make the commit yourself.
main: #e02828
sub: #69176b
bg: #fffdd0
caret: #99de1e
text: #808080
error: #4d0463
extra error: #a62626
Give that a try.

**Comment by Miodec** [comment]
Closed by #2317

**Pull request closed without merging**
