### PR TITLE
A new minimalistic theme

### PR DESCRIPTION
**Pull request by Fluffy-Cookie**
### The screenshots for extra awesomeness!

Screenshot 2022-02-18 151941

Screenshot 2022-02-18 152415

### The charcoal and pure white go perfectly with each other

Screenshot 2022-02-18 152814

### CODE REVIEW

**Comment by Miodec** [comment]
Sorry, the color scheme is pretty much the same as the `paper` theme.

**Comment by Fluffy-Cookie** [comment]
Hmm, I did notice that thought that punch was different, anyway I am going to see this as just a prototype maybe I will do one more changes and BTW I would like to know how we create custom colors for the menu buttons
Screenshot 2022-02-19 115809

It was hard NVM we can make a better one!

**Comment by Miodec** [comment]
Here is the theme you are looking at: 

https://github.com/Miodec/monkeytype/blob/master/frontend/static/themes/aether.css

**Comment by Fluffy-Cookie** [comment]
Thanks, I'll look into it!

**Pull request closed without merging**
