### PR TITLE
Fix Image Issue

### PR DESCRIPTION
**Pull request by teddinotteddy**
### Description
Fixed image issue where mtsocial.png wouldn't show on Discord or Twitter.

### CODE REVIEW

**Review by Miodec — APPROVED** [review]

**Comment by Miodec** [comment]
Are you sure this is the correct path? Im not sure if 'static' is needed there?

**Comment by teddinotteddy** [comment]
@Miodec It might not be needed, but I removed that anyway.

**Comment by Miodec** [comment]
Might? So, is this even tested?

**Comment by teddinotteddy** [comment]
@Miodec I'm so sorry. That was very poor choice of words on my part. I was rushing through this as I am in school right now but yes, I just double checked with the new path. It does indeed work. Sorry for the miscommunication.

**Comment by Miodec** [comment]
Alright, sounds good

**Pull request merged**
