### PR TITLE
added IFK ez-mode theme

### PR DESCRIPTION
**Pull request by kraiztmatte**
### Description

Hi I'm adding ifk ez-mode theme based on this [keycap set](https://geekhack.org/index.php?topic=113393.0), this actually was my friend set, and he ask me to add PR for the theme since he couldn't do or understands git stuff, so i help him.

asd

### Checklist 
- [✔️  ] I have read the [`CODE_OF_CONDUCT.md`](https://github.com/Miodec/monkeytype/blob/master/CODE_OF_CONDUCT.md) and the [`CONTRIBUTING.md`](https://github.com/Miodec/monkeytype/blob/master/CONTRIBUTING.md)
- [✔️ ] I checked if my PR has any bugs or other issues that could reduce the stability of the project
- [✔️ ] I understand that the maintainer has the right to reject my contribution and it may not get accepted.
- [✔️ ] If my PR is a new language or theme I modified the appropriate files to incorporate the language or theme

### CODE REVIEW

**Comment by Miodec** [comment]
I'm not sure if I'm going to merge this as this looks too similar to `ms cupcakes` that is already live on the website :(

**Comment by kraiztmatte** [comment]
> I'm not sure if I'm going to merge this as this looks too similar to `ms cupcakes` that is already live on the website :(

I don't think its too similar, yeah it same clump of color, but in different color scheme, maybe you could reconsider little bit more, here's the color scheme:

https://monkeytype.com/?customTheme=%23f5f5f5%2C%230171cd%2C%234ddb47%2C%23dd51ad%2C%230171cd%2C%234ddb47%2C%2342ba3b%2C%234ddb47%2C%2342ba3b

ez-mode

asddxz
Screen_Shot_2021-06-23_at_14 18 04
aaa


compared with cupcake

safdff
sdfsdf

**Comment by Miodec** [comment]
I disagree. I know they are different shades but still the general colors are too close to ms cupcake.

**Comment by kraiztmatte** [comment]
alright, thank you

**Pull request closed without merging**
