### PR TITLE
Display Dates in 12 Hour Format Instead of 24

### PR DESCRIPTION
**Pull request by UnrealApex**
### Description
Formatted dates so they are in the 12 hour format.

### CODE REVIEW

**Comment by UnrealApex** [comment]
@Miodec I acknowledge that using the 24 hour format makes the dates and site look more minimal. If you think using 12 hour dates will make the UI cluttered, we could have the 12 hour dates in tooltips.

**Review by Miodec — CHANGES_REQUESTED** [review]
Move 12h time to tooltips

**Comment by Bruception** [comment]
Why not make this a configuration?

**Comment by Miodec** [comment]
> Why not make this a configuration?

Because this would be an overly specific setting - i want to avoid things like that, there is already a ton of settings.

**Comment by Bruception** [comment]
The build is failing. You will need to address the issues.

**Comment by UnrealApex** [comment]
> The build is failing. You will need to address the issues.

Yep, I'll inspect it.

**Comment by strafe** [comment]
Might be a good time to drop `moment` since it's not being developed anymore, and use JS's native methods to display dates & times in the user's locale.

**Comment by Miodec** [comment]
> Might be a good time to drop `moment` since it's not being developed anymore, and use JS's native methods to display dates & times in the user's locale.

Good idea. Added #2667

**Comment by Miodec** [comment]
Closing due to inactivity

**Comment by UnrealApex** [comment]
> > The build is failing. You will need to address the issues.
> 
> Yep, I'll inspect it.

Lost access to my dev machine, I'll see if I get it back and fix some of the build errors soon.

**Pull request closed without merging**
