### PR TITLE
Finnish wordlist

### PR DESCRIPTION
**Pull request by LediM0nsteri**
List contains some finnish words and some words are really basic.

### CODE REVIEW

**Comment by Miodec** [comment]
Make sure to name the language correctly inside the file, and add it to the `list.json` file, otherwise it wont work

**Comment by LediM0nsteri** [comment]
Now the language is named right in the finnish.json file and finnish is added to list.json.

**Comment by Miodec** [comment]
Looks like you still forgot to commit the list file - ill do it.

**Comment by LediM0nsteri** [comment]
I'm kinda new to github and I thought I edited finnish into the list.json file but maybe I didn't commit it. My bad anyways. You are doing great job on this project, thank you!

**Pull request merged**
