### PR TITLE
Added wikipedia mode to funbox

### PR DESCRIPTION
**Pull request by Jonny-exe**
### Description

Added wikipedia mode to funbox. In this mode you get random sentences from wikipedia articles, using wikipedia's [API](https://www.mediawiki.org/wiki/API:Main_page).

Closes #
#306

### CODE REVIEW

**Comment by Miodec** [comment]
That was quite fast, testing now.

**Comment by Miodec** [comment]
So, biggest issue i see so far is that if the section is very short, and your mode is set to time 30 for example, after running out of Wikipedia words it will just revert to adding random words.

Writing it just now i realised that it will fail regardless of how long the Wikipedia text is after 100 words, because it doesn't work with the `addWord` function. I remember i ran into this issue when trying to fix the poetry funbox. Im not sure whats the approach here.

**Comment by Jonny-exe** [comment]
I hadn't considered that. Maybe loading another text whenever the user is close to finishing? Or maybe just adding the same text from the start? I'll try to think of something. I'll also have a look at the addWord function and try to make it work with wikipedia sections.

**Comment by Jonny-exe** [comment]
I'm not able to reproduce the error with `addWord`. I have tried: 
1. Going to funbox, wikipedia.
2. Selecting time mode
Whenever the section is to short random words are added until the time is finished.

What's the expected behaviour?

**Comment by Miodec** [comment]
Well, i dont know what should be the expected behavior. It doesn't make sense to have a shorter text than how long the test is. And reverting to random words seems... not like the solution. Im not sure what to do here, and the poetry funbox.

**Comment by Jonny-exe** [comment]
Would loading a new Section be a viable solution?
Instaed of loading random words you could load a new section whenever the user is close to finishing.

**Comment by Miodec** [comment]
Hm.. Maybe it could work.

**Comment by Jonny-exe** [comment]
I changed it, so it will fetch a new section whenever the user has 20 words left. Also (in words mode), at the beginning it will fetch as many sections as it needs until it has reached the desired words amount.
I think it is a viable solution, but tell me what you think. If it is ok, I can do the same for poems.

**Review by thuongtruong1009 — APPROVED** [review]
Well done. Keep contributing.

**Comment by Miodec** [comment]
image

Broke on a 30 second test when the wiki article was short.

**Comment by Miodec** [comment]
Adding more words works well. Im still thinking how it would perform with slow internet, but i guess its fine for now. I think for time mode i would always make it generate at least 100 words so it fills the screen correctly.

image

If you're feeling extra awesome, you could also make this change for the poetry funbox, but its up to you.

**Review by Miodec — APPROVED** [review]

**Comment by Miodec** [comment]
Nice work

**Pull request merged**
