### PR TITLE
added overflow theme

### PR DESCRIPTION
**Pull request by TechPenguineer**
### Description

Added new overflow colour theme

Closes #

### CODE REVIEW

**Comment by Miodec** [comment]
Please include a screenshot

**Comment by TechPenguineer** [comment]
> Please include a screenshot

Will do!

**Comment by Miodec** [comment]
Just checked it, seems like the colors are kinda backwards, especially looking at the test config, the selected option is not readable. 
image

Also as per the contributing guide, theme text colors should be as close to white or black.

**Comment by Miodec** [comment]
image

Favicon also unreadable

**Pull request merged**
